# Generated by Django 5.0.7 on 2023-08-20 16:00

from django.db import migrations
from django.contrib.auth.hashers import make_password


def popular_datos_iniciales(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Exercise = apps.get_model('core', 'Exercise')
    WorkoutDay = apps.get_model('core', 'WorkoutDay')
    WorkoutExercise = apps.get_model('core', 'WorkoutExercise')

    # 1. Crear usuario de prueba
    test_user, created = User.objects.get_or_create(
        username='test',
        defaults={
            'password': make_password('test'),
            'is_superuser': True,
            'is_staff': True
        }
    )
    if not created:
        # Si el usuario ya existe, nos aseguramos de que la contraseña sea la correcta
        test_user.password = make_password('test')
        test_user.save()

    # 2. Crear ejercicios de ejemplo (asegurándonos de que no existan)
    ejercicios_data = [
        {'nombre': 'Press de Banca', 'descripcion': 'Ejercicio de pecho con barra.',
            'musculo_principal': 'Pectoral'},
        {'nombre': 'Sentadillas', 'descripcion': 'Ejercicio de piernas con barra.',
            'musculo_principal': 'Piernas'},
        {'nombre': 'Peso Muerto', 'descripcion': 'Levantamiento de peso desde el suelo.',
            'musculo_principal': 'Espalda'},
        {'nombre': 'Press Militar', 'descripcion': 'Ejercicio de hombros con barra.',
            'musculo_principal': 'Hombros'},
        {'nombre': 'Dominadas', 'descripcion': 'Levantamiento del cuerpo en barra fija.',
            'musculo_principal': 'Espalda'},
        {'nombre': 'Remo con Barra', 'descripcion': 'Ejercicio de espalda con barra.',
            'musculo_principal': 'Espalda'},
        {'nombre': 'Curl de Bíceps', 'descripcion': 'Ejercicio de brazos con mancuernas.',
            'musculo_principal': 'Bíceps'},
        {'nombre': 'Press Francés', 'descripcion': 'Ejercicio de tríceps con barra.',
            'musculo_principal': 'Tríceps'},
        {'nombre': 'Elevaciones Laterales',
            'descripcion': 'Ejercicio de hombros con mancuernas.', 'musculo_principal': 'Hombros'},
        {'nombre': 'Prensa de Piernas', 'descripcion': 'Ejercicio de piernas en máquina.',
            'musculo_principal': 'Piernas'},
    ]

    ejercicios_creados = []
    for ejercicio_info in ejercicios_data:
        ejercicio, created = Exercise.objects.get_or_create(**ejercicio_info)
        ejercicios_creados.append(ejercicio)

    # 3. Crear rutinas para el usuario 'test'
    # Rutina de Lunes
    dia_lunes, _ = WorkoutDay.objects.get_or_create(
        usuario=test_user, dia_de_la_semana='LUN')
    WorkoutExercise.objects.create(
        # Press de Banca
        workout_day=dia_lunes, ejercicio=ejercicios_creados[0], series=4, repeticiones=8, peso_estimado=50)
    WorkoutExercise.objects.create(
        # Press Militar
        workout_day=dia_lunes, ejercicio=ejercicios_creados[3], series=3, repeticiones=10, peso_estimado=30)
    WorkoutExercise.objects.create(
        # Press Francés
        workout_day=dia_lunes, ejercicio=ejercicios_creados[7], series=3, repeticiones=12, peso_estimado=20)

    # Rutina de Miércoles
    dia_miercoles, _ = WorkoutDay.objects.get_or_create(
        usuario=test_user, dia_de_la_semana='MIE')
    WorkoutExercise.objects.create(
        # Sentadillas
        workout_day=dia_miercoles, ejercicio=ejercicios_creados[1], series=4, repeticiones=10, peso_estimado=80)
    WorkoutExercise.objects.create(
        # Peso Muerto
        workout_day=dia_miercoles, ejercicio=ejercicios_creados[2], series=3, repeticiones=8, peso_estimado=100)
    WorkoutExercise.objects.create(
        # Prensa de Piernas
        workout_day=dia_miercoles, ejercicio=ejercicios_creados[9], series=3, repeticiones=12, peso_estimado=120)

    # Rutina de Viernes
    dia_viernes, _ = WorkoutDay.objects.get_or_create(
        usuario=test_user, dia_de_la_semana='VIE')
    WorkoutExercise.objects.create(
        # Dominadas
        workout_day=dia_viernes, ejercicio=ejercicios_creados[4], series=4, repeticiones=8, peso_estimado=0)
    WorkoutExercise.objects.create(
        # Remo con Barra
        workout_day=dia_viernes, ejercicio=ejercicios_creados[5], series=3, repeticiones=10, peso_estimado=40)
    WorkoutExercise.objects.create(
        # Curl de Bíceps
        workout_day=dia_viernes, ejercicio=ejercicios_creados[6], series=3, repeticiones=12, peso_estimado=10)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_datos_iniciales),
    ]
