# Generated by Django 5.2.5 on 2025-08-21 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_popular_los_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
