# Generated by Django 5.2.5 on 2025-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workoutsession_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutday',
            name='nombre',
            field=models.CharField(blank=True, default='Mi Rutina', max_length=100, null=True),
        ),
    ]
