# Generated by Django 5.2.5 on 2025-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workoutday_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
